/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
/**
 *
 * @author Mr. Sagar Sangam Rai
 */
import java.util.Properties;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.io.ByteArrayOutputStream;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.text.*;
import java.io.File;
import java.io.FileInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;



public class employee_info extends javax.swing.JFrame {
 Connection conn=null;
 ResultSet rs=null;
 PreparedStatement pst=null;
    /**
     * Creates new form employee_info
     */
    public employee_info() {
        initComponents();
        conn=javaconnect.ConnecrDb();
        Update_table();
        Fillcombo();
        currentDate();
    }
    
    public void comboselect(){
        int d=ComboBox_name.getSelectedIndex();
        if(d==1){
            Userinfo s=new Userinfo();
            s.setVisible(true);
        }
        if(d==2){
            Login_ifrrame l=new Login_ifrrame();
            l.setVisible(true);
        }
    }
    public void currentDate(){
        Calendar cal=new GregorianCalendar();
        int month=cal.get(Calendar.MONTH);
        int year=cal.get(Calendar.YEAR);
        int day=cal.get(Calendar.DAY_OF_MONTH);
        date_txt.setText("Date "+year+"/"+(month+1)+"/"+day);
        
        int second=cal.get(Calendar.SECOND);
        int minute=cal.get(Calendar.MINUTE);
        int hour=cal.get(Calendar.HOUR);
        time_txt.setText("Time "+hour+":"+(minute)+":"+second);
        
    }
    
    private void Update_table(){
        try{
       String sql="select * from Employeeinfo";
       pst=conn.prepareStatement(sql);
       rs=pst.executeQuery();
       Table_Employee.setModel(DbUtils.resultSetToTableModel(rs));
       
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}
        finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
    
    }
    public void close(){
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    private void Fillcombo(){
        try{
            String sql="select * from Employeeinfo";
             pst=conn.prepareStatement(sql);
             rs=pst.executeQuery();
             
             while(rs.next()){
                 String name=rs.getString("EmpID");
                 ComboBox_name.addItem(name);
             }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_age = new javax.swing.JTextField();
        txt_surname = new javax.swing.JTextField();
        Cmd_save = new javax.swing.JButton();
        txt_update = new javax.swing.JButton();
        Cmd_clear = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ComboBox_name = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_EmpID = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txt_filepath = new javax.swing.JTextField();
        txt_contact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        combo_post = new javax.swing.JComboBox();
        join_date = new com.toedter.calendar.JDateChooser();
        txt_address = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_about = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        Cmd_delete = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        image = new javax.swing.JLabel();
        lbl_age = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_EmpID = new javax.swing.JLabel();
        lbl_surname = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_gender = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbl_contact = new javax.swing.JLabel();
        lbl_joindate = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbl_post = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbl_about = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Employee = new javax.swing.JTable();
        Cmd_print = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        subject = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        To = new javax.swing.JTextField();
        path_attach = new javax.swing.JTextField();
        attach = new javax.swing.JButton();
        name_attach = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Text = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        fetch_inbox = new javax.swing.JButton();
        all_messages = new javax.swing.JLabel();
        content_message = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        date_txt = new javax.swing.JMenu();
        time_txt = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setForeground(new java.awt.Color(51, 0, 255));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Register Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Pristina", 1, 24), new java.awt.Color(204, 0, 51))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 51, 102));

        Cmd_save.setText("Save");
        Cmd_save.setToolTipText("Save the datas of Form above");
        Cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_saveActionPerformed(evt);
            }
        });

        txt_update.setText("Update");
        txt_update.setToolTipText("Update the data of form above");
        txt_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_updateActionPerformed(evt);
            }
        });

        Cmd_clear.setText("Clear");
        Cmd_clear.setToolTipText("Clear the form above");
        Cmd_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_clearActionPerformed(evt);
            }
        });

        txt_search.setToolTipText("Search Employee from ID,Name and Surname");
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });

        jLabel5.setText("Search");

        ComboBox_name.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "             " }));
        ComboBox_name.setToolTipText("Browse with Emp ID");
        ComboBox_name.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                ComboBox_namePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        ComboBox_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_nameActionPerformed(evt);
            }
        });

        jLabel1.setText("Employee ID");

        jLabel2.setText("Name");

        jLabel3.setText("Surname");

        jLabel4.setText("Age");

        txt_EmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmpIDActionPerformed(evt);
            }
        });

        jButton2.setText("Attach Image");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txt_filepath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filepathActionPerformed(evt);
            }
        });

        jLabel6.setText("Address");

        jLabel10.setText("Contact No.");

        jLabel11.setText("Join Date");

        jLabel12.setText("Post");

        combo_post.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chief", "Manager", "Enginneer", "Worker" }));

        jLabel16.setText("Email");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Female");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Male");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        txt_about.setColumns(20);
        txt_about.setRows(5);
        txt_about.setToolTipText("Write Something Unique about Worker");
        jScrollPane6.setViewportView(txt_about);

        jLabel18.setText("Other Information (About him/her)");

        Cmd_delete.setText("Delete");
        Cmd_delete.setToolTipText("Delete the selected row of table.");
        Cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_deleteActionPerformed(evt);
            }
        });

        jLabel26.setText("Password");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel26))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton1))
                                    .addComponent(txt_email)
                                    .addComponent(combo_post, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(join_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_contact)
                                    .addComponent(txt_address)
                                    .addComponent(txt_surname)
                                    .addComponent(txt_name)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txt_EmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_password)))
                            .addComponent(jLabel13)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(Cmd_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Cmd_save, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_update, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Cmd_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txt_filepath, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ComboBox_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(ComboBox_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_EmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2)))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(join_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(combo_post, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_filepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cmd_clear)
                    .addComponent(Cmd_save)
                    .addComponent(txt_update)
                    .addComponent(Cmd_delete))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poor Richard", 0, 24), new java.awt.Color(0, 102, 255))); // NOI18N

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1.setLayer(image, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbl_age.setText("Age");

        lbl_name.setText("Name");

        lbl_EmpID.setText("Employee ID");

        lbl_surname.setText("Surname");

        jLabel14.setText("Full Name :");

        jLabel15.setText("EmployeeID:");

        jLabel17.setText("Age :");

        lbl_gender.setText("Gender");

        jLabel20.setText("Gender:");

        jLabel19.setText("Address:");

        lbl_address.setText("Address");

        jLabel21.setText("Contact No.:");

        lbl_contact.setText("Contact No.");

        lbl_joindate.setText("Join Date");

        jLabel23.setText("Join Date:");

        jLabel22.setText("Post:");

        lbl_post.setText("Post");

        jLabel24.setText("Email:");

        lbl_email.setText("Email");

        jLabel25.setText("About :");

        lbl_about.setText("About ");

        jLabel27.setText("Password: ");

        lbl_password.setText("Password");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_address)
                            .addComponent(lbl_name)
                            .addComponent(lbl_EmpID)
                            .addComponent(lbl_surname)
                            .addComponent(lbl_age)
                            .addComponent(lbl_gender)))
                    .addComponent(jLabel25)
                    .addComponent(lbl_about)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_password)
                            .addComponent(lbl_email)
                            .addComponent(lbl_post)
                            .addComponent(lbl_joindate)
                            .addComponent(lbl_contact))))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_EmpID)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name)
                    .addComponent(jLabel14))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_surname))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_age))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_gender)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lbl_address))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lbl_contact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_joindate)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(lbl_post))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lbl_email))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lbl_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_about)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel4);

        Table_Employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_Employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_EmployeeMouseClicked(evt);
            }
        });
        Table_Employee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Table_EmployeeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Table_EmployeeKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Employee);

        Cmd_print.setText("Print Table");
        Cmd_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(Cmd_print, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cmd_print)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Empoyee Table", jPanel6);

        jButton3.setText("Send");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("To");

        jLabel8.setText("Subject");

        To.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToActionPerformed(evt);
            }
        });

        path_attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                path_attachActionPerformed(evt);
            }
        });

        attach.setText("Attach");
        attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachActionPerformed(evt);
            }
        });

        name_attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_attachActionPerformed(evt);
            }
        });

        jLabel9.setText("Write name of file");

        Text.setColumns(20);
        Text.setRows(5);
        jScrollPane5.setViewportView(Text);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(To, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(attach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(path_attach, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name_attach, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addGap(0, 391, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(To))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attach)
                    .addComponent(path_attach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(name_attach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(19, 19, 19))
        );

        jTabbedPane2.addTab("Send Mail", jPanel1);

        fetch_inbox.setText("Get New Message Notifications");
        fetch_inbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetch_inboxActionPerformed(evt);
            }
        });

        content_message.setText("If message have attachment, then It is saved in E:\\Attachment");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(all_messages))
                    .addComponent(fetch_inbox, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(content_message, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fetch_inbox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content_message)
                .addGap(125, 125, 125)
                .addComponent(all_messages)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Inbox Notifications", jPanel2);

        jScrollPane4.setViewportView(jTabbedPane2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3)
                .addGap(197, 197, 197))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 828, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel5);

        jTabbedPane1.addTab("Employee Iinformation", jScrollPane2);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("New");
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Close");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        date_txt.setText("Date");
        jMenuBar1.add(date_txt);

        time_txt.setText("Time");
        jMenuBar1.add(time_txt);

        jMenu3.setText("Help");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Help File");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1199, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        close();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
               try{
                   Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Users\\Mr. Sagar Sangam Rai\\Desktop\\desktop\\wanted.pdf");
                   
               }catch(Exception e){
                   JOptionPane.showMessageDialog(null, e);
               }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
            System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void fetch_inboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetch_inboxActionPerformed
        String host = "pop.gmail.com";
        String port = "995";
        String userName = "companysagavision@gmail.com";
        String password = "thankyougoogle";

        String saveDirectory = "E:/Attachment";

        EmailAttachmentReciever receiver = new EmailAttachmentReciever();
        receiver.setSaveDirectory(saveDirectory);
        receiver.downloadEmailAttachments(host, port, userName, password);
        content_message.setText(EmailAttachmentReciever.sagar+EmailAttachmentReciever.sagar2+EmailAttachmentReciever.sagar3+EmailAttachmentReciever.sagar4);
        
    }//GEN-LAST:event_fetch_inboxActionPerformed

    private void attachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachActionPerformed
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        attachment_path=f.getAbsolutePath();
        path_attach.setText(attachment_path);
    }//GEN-LAST:event_attachActionPerformed

    private void path_attachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_path_attachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_path_attachActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String To_add=To.getText();
        String Subject=subject.getText();
        String Text_content=Text.getText();

        Properties props=new Properties();
        props.put("mail.smtp.host","smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port","465");
        props.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.port","465");

        Session session=Session.getDefaultInstance(props,
            new javax.mail.Authenticator(){
                protected PasswordAuthentication getPasswordAuthentication(){
                    return new PasswordAuthentication("companysagavision@gmail.com","thankyougoogle");
                }
            }
        );

        try{
            Message message=new MimeMessage(session);
            message.setFrom(new InternetAddress("companysagavision@gmail.com"));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(To_add));
            message.setSubject(Subject);
            MimeBodyPart messageBodyPart=new MimeBodyPart();
            messageBodyPart.setText(Text_content);
            Multipart multipart=new MimeMultipart();
            multipart.addBodyPart(messageBodyPart);

            messageBodyPart=new MimeBodyPart();
            javax.activation.DataSource source=new FileDataSource(attachment_path);
            messageBodyPart.setDataHandler(new DataHandler (source));
            messageBodyPart.setFileName(name_attach.getText());
            multipart.addBodyPart(messageBodyPart);
            message.setContent(multipart);

            Transport.send(message);
            JOptionPane.showMessageDialog(null," message sent");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Cmd_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_printActionPerformed
        MessageFormat header=new MessageFormat("Report Print");
        MessageFormat footer=new MessageFormat("Page{0,number,integer}");
        try{
            Table_Employee.print(JTable.PrintMode.NORMAL,header,footer);
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot Print %s%n",e.getMessage());
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_Cmd_printActionPerformed

    private void txt_filepathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filepathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filepathActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        txt_filepath.setText(filename);
        try{
            File image=new File(filename);
            FileInputStream fis =new FileInputStream(image);
            ByteArrayOutputStream bos=new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            for(int readNum; (readNum=fis.read(buf))!=-1;){
                bos.write(buf,0,readNum);
                person_image=bos.toByteArray();

            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_EmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmpIDActionPerformed

    private void ComboBox_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_nameActionPerformed

    private void ComboBox_namePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboBox_namePopupMenuWillBecomeInvisible
       // comboselect();
        String tmp=(String)ComboBox_name.getSelectedItem();
        String sql="select * from Employeeinfo where EmpID=?";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1,tmp);
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("EmpID");
                txt_EmpID.setText(add1);
                lbl_EmpID.setText(add1);
                String add2=rs.getString("name");
                txt_name.setText(add2);
                lbl_name.setText(add2);
                String add3=rs.getString("surname");
                txt_surname.setText(add3);
                lbl_surname.setText(add3);
                String add4=rs.getString("age");
                txt_age.setText(add4);
                lbl_age.setText(add4);
                String add5=rs.getString("Gender");
                lbl_gender.setText(add5);
                String add6=rs.getString("Address");
                txt_address.setText(add6);
                lbl_address.setText(add6);
                String add7=rs.getString("Contact");
                txt_contact.setText(add7);
                lbl_contact.setText(add7);
                String add8=rs.getString("JDate");
                lbl_joindate.setText(add8);
                String add9=rs.getString("Post");
                lbl_post.setText(add9);
                String add10=rs.getString("Email");
                txt_email.setText(add10);
                lbl_email.setText(add10);
                To.setText(add10);
                String add12=rs.getString("password");
                txt_password.setText(add12);
                lbl_password.setText(add12);
                byte[] imagedata=rs.getBytes("image");
                format =new ImageIcon(imagedata);
                image.setIcon(format);
                
                String add11=rs.getString("About");
                txt_about.setText(add11);
                lbl_about.setText(add11);
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_ComboBox_namePopupMenuWillBecomeInvisible

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        try{
            String sql="select * from Employeeinfo where name=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
               String add1=rs.getString("EmpID");
                txt_EmpID.setText(add1);
                lbl_EmpID.setText(add1);
                String add2=rs.getString("name");
                txt_name.setText(add2);
                lbl_name.setText(add2);
                String add3=rs.getString("surname");
                txt_surname.setText(add3);
                lbl_surname.setText(add3);
                String add4=rs.getString("age");
                txt_age.setText(add4);
                lbl_age.setText(add4);
                String add5=rs.getString("Gender");
                lbl_gender.setText(add5);
                String add6=rs.getString("Address");
                txt_address.setText(add6);
                lbl_address.setText(add6);
                String add7=rs.getString("Contact");
                txt_contact.setText(add7);
                lbl_contact.setText(add7);
                String add8=rs.getString("JDate");
                lbl_joindate.setText(add8);
                String add9=rs.getString("Post");
                lbl_post.setText(add9);
                String add10=rs.getString("Email");
                txt_email.setText(add10);
                lbl_email.setText(add10);
                To.setText(add10);
                String add12=rs.getString("password");
                txt_password.setText(add12);
                lbl_password.setText(add12);
                byte[] imagedata=rs.getBytes("image");
                format =new ImageIcon(imagedata);
                image.setIcon(format);
                
                String add11=rs.getString("About");
                txt_about.setText(add11);
                lbl_about.setText(add11);
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }

        try{
            String sql="select * from Employeeinfo where EmpID=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
               String add1=rs.getString("EmpID");
                txt_EmpID.setText(add1);
                lbl_EmpID.setText(add1);
                String add2=rs.getString("name");
                txt_name.setText(add2);
                lbl_name.setText(add2);
                String add3=rs.getString("surname");
                txt_surname.setText(add3);
                lbl_surname.setText(add3);
                String add4=rs.getString("age");
                txt_age.setText(add4);
                lbl_age.setText(add4);
                String add5=rs.getString("Gender");
                lbl_gender.setText(add5);
                String add6=rs.getString("Address");
                txt_address.setText(add6);
                lbl_address.setText(add6);
                String add7=rs.getString("Contact");
                txt_contact.setText(add7);
                lbl_contact.setText(add7);
                String add8=rs.getString("JDate");
                lbl_joindate.setText(add8);
                String add9=rs.getString("Post");
                lbl_post.setText(add9);
                String add10=rs.getString("Email");
                txt_email.setText(add10);
                lbl_email.setText(add10);
                To.setText(add10);
                String add12=rs.getString("password");
                txt_password.setText(add12);
                lbl_password.setText(add12);
                byte[] imagedata=rs.getBytes("image");
                format =new ImageIcon(imagedata);
                image.setIcon(format);
                
                String add11=rs.getString("About");
                txt_about.setText(add11);
                lbl_about.setText(add11);
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }

        try{
            String sql="select * from Employeeinfo where surname=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
               String add1=rs.getString("EmpID");
                txt_EmpID.setText(add1);
                lbl_EmpID.setText(add1);
                String add2=rs.getString("name");
                txt_name.setText(add2);
                lbl_name.setText(add2);
                String add3=rs.getString("surname");
                txt_surname.setText(add3);
                lbl_surname.setText(add3);
                String add4=rs.getString("age");
                txt_age.setText(add4);
                lbl_age.setText(add4);
                String add5=rs.getString("Gender");
                lbl_gender.setText(add5);
                String add6=rs.getString("Address");
                txt_address.setText(add6);
                lbl_address.setText(add6);
                String add7=rs.getString("Contact");
                txt_contact.setText(add7);
                lbl_contact.setText(add7);
                String add8=rs.getString("JDate");
                lbl_joindate.setText(add8);
                String add9=rs.getString("Post");
                lbl_post.setText(add9);
                String add10=rs.getString("Email");
                txt_email.setText(add10);
                lbl_email.setText(add10);
                To.setText(add10);
                String add12=rs.getString("password");
                txt_password.setText(add12);
                lbl_password.setText(add12);
                byte[] imagedata=rs.getBytes("image");
                format =new ImageIcon(imagedata);
                image.setIcon(format);
                
                String add11=rs.getString("About");
                txt_about.setText(add11);
                lbl_about.setText(add11);
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
         try{
            String sql="select * from Employeeinfo where Email=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
               String add1=rs.getString("EmpID");
                txt_EmpID.setText(add1);
                lbl_EmpID.setText(add1);
                String add2=rs.getString("name");
                txt_name.setText(add2);
                lbl_name.setText(add2);
                String add3=rs.getString("surname");
                txt_surname.setText(add3);
                lbl_surname.setText(add3);
                String add4=rs.getString("age");
                txt_age.setText(add4);
                lbl_age.setText(add4);
                String add5=rs.getString("Gender");
                lbl_gender.setText(add5);
                String add6=rs.getString("Address");
                txt_address.setText(add6);
                lbl_address.setText(add6);
                String add7=rs.getString("Contact");
                txt_contact.setText(add7);
                lbl_contact.setText(add7);
                String add8=rs.getString("JDate");
                lbl_joindate.setText(add8);
                String add9=rs.getString("Post");
                lbl_post.setText(add9);
                String add10=rs.getString("Email");
                txt_email.setText(add10);
                lbl_email.setText(add10);
                 To.setText(add10);
               String add12=rs.getString("password");
                txt_password.setText(add12);
                lbl_password.setText(add12);
                byte[] imagedata=rs.getBytes("image");
                format =new ImageIcon(imagedata);
                image.setIcon(format);
                
                String add11=rs.getString("About");
                txt_about.setText(add11);
                lbl_about.setText(add11);
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_txt_searchActionPerformed

    private void Cmd_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_clearActionPerformed
        txt_EmpID.setText("");
        txt_name.setText("");
        txt_surname.setText("");
        txt_age.setText("");
        txt_address.setText("");
        txt_contact.setText("");
        txt_email.setText("");
        txt_about.setText("");
        txt_password.setText("");
    }//GEN-LAST:event_Cmd_clearActionPerformed

    private void txt_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_updateActionPerformed
        try{
            String value1=txt_EmpID.getText();
            String value2=txt_name.getText();
            String value3=txt_surname.getText();
            String value4=txt_age.getText();
            String value5=gender;
            String value6=txt_address.getText();
            String value7=txt_contact.getText();
            String value8=((JTextField)join_date.getDateEditor().getUiComponent()).getText();
            String value9=combo_post.getSelectedItem().toString();
            String value10=txt_email.getText();
            String value13=txt_password.getText();
            String value12=txt_about.getText();

            String sql="update employeeinfo set EmpID='"+value1+"',name='"+value2+"',surname='"+value3+"',age='"+value4+"',Gender='"+value5+"'"
                    + ",Address='"+value6+"',Contact='"+value7+"',JDate='"+value8+"',Post='"+value9+"',Email='"+value10+"',About='"+value12+"',password='"+value13+"' where EmpID='"+value1+"' ";
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Updated");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
        Update_table();
    }//GEN-LAST:event_txt_updateActionPerformed

    private void Cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_deleteActionPerformed
        int p=JOptionPane.showConfirmDialog(null,"Do you really want to Delete?","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
            String sql="delete from Employeeinfo where EmpID=?";
            try{
                pst=conn.prepareStatement(sql);
                pst.setString(1,txt_EmpID.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Deleted");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
            Update_table();
        }
    }//GEN-LAST:event_Cmd_deleteActionPerformed

    private void Cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_saveActionPerformed
        try{
            String sql="Insert into Employeeinfo (EmpID,name,surname,age,gender,Address,Contact,JDate,Post,Email,Image,About,password) values (?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1, txt_EmpID.getText());
            pst.setString(2, txt_name.getText());
            pst.setString(3, txt_surname.getText());
            pst.setString(4, txt_age.getText());
            pst.setString(5, gender);
            pst.setString(6, txt_address.getText());
            pst.setString(7, txt_contact.getText());
            pst.setString(8,((JTextField)join_date.getDateEditor().getUiComponent()).getText());
            pst.setString(9, combo_post.getSelectedItem().toString());
            pst.setString(10, txt_email.getText());
            pst.setString(13, txt_password.getText());
            pst.setBytes(11,person_image);
            pst.setString(12,txt_about.getText());
    
            pst.execute();
            JOptionPane.showMessageDialog(null,"Saved");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
        Update_table();
    }//GEN-LAST:event_Cmd_saveActionPerformed

    private void ToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToActionPerformed

    private void name_attachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_attachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_attachActionPerformed

    private void Table_EmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_EmployeeMouseClicked
 try{
            int row=Table_Employee.getSelectedRow();
            String Table_click=(Table_Employee.getModel().getValueAt(row,0).toString());
            String sql="select * from Employeeinfo where EmpID='"+Table_click+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
              String add1=rs.getString("EmpID");
                txt_EmpID.setText(add1);
                lbl_EmpID.setText(add1);
                String add2=rs.getString("name");
                txt_name.setText(add2);
                lbl_name.setText(add2);
                String add3=rs.getString("surname");
                txt_surname.setText(add3);
                lbl_surname.setText(add3);
                String add4=rs.getString("age");
                txt_age.setText(add4);
                lbl_age.setText(add4);
                String add5=rs.getString("Gender");
                lbl_gender.setText(add5);
                String add6=rs.getString("Address");
                txt_address.setText(add6);
                lbl_address.setText(add6);
                String add7=rs.getString("Contact");
                txt_contact.setText(add7);
                lbl_contact.setText(add7);
                String add8=rs.getString("JDate");
                lbl_joindate.setText(add8);
                String add9=rs.getString("Post");
                lbl_post.setText(add9);
                String add10=rs.getString("Email");
                txt_email.setText(add10);
                lbl_email.setText(add10);
                 To.setText(add10);
               String add12=rs.getString("password");
                txt_password.setText(add12);
                lbl_password.setText(add12);
                byte[] imagedata=rs.getBytes("image");
                format =new ImageIcon(imagedata);
                image.setIcon(format);
                
                String add11=rs.getString("About");
                txt_about.setText(add11);
                lbl_about.setText(add11);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }    }//GEN-LAST:event_Table_EmployeeMouseClicked

    private void Table_EmployeeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_EmployeeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Table_EmployeeKeyPressed

    private void Table_EmployeeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_EmployeeKeyReleased
          if((evt.getKeyCode()==KeyEvent.VK_UP)||(evt.getKeyCode()==KeyEvent.VK_DOWN)){
              try{
                 int row=Table_Employee.getSelectedRow();
            String Table_click=(Table_Employee.getModel().getValueAt(row,0).toString());
            String sql="select * from Employeeinfo where EmpID='"+Table_click+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("EmpID");
                txt_EmpID.setText(add1);
                lbl_EmpID.setText(add1);
                String add2=rs.getString("name");
                txt_name.setText(add2);
                lbl_name.setText(add2);
                String add3=rs.getString("surname");
                txt_surname.setText(add3);
                lbl_surname.setText(add3);
                String add4=rs.getString("age");
                txt_age.setText(add4);
                lbl_age.setText(add4);
                String add5=rs.getString("Gender");
                lbl_gender.setText(add5);
                String add6=rs.getString("Address");
                txt_address.setText(add6);
                lbl_address.setText(add6);
                String add7=rs.getString("Contact");
                txt_contact.setText(add7);
                lbl_contact.setText(add7);
                String add8=rs.getString("JDate");
                lbl_joindate.setText(add8);
                String add9=rs.getString("Post");
                lbl_post.setText(add9);
                String add10=rs.getString("Email");
                txt_email.setText(add10);
                lbl_email.setText(add10);
                 To.setText(add10);
               String add12=rs.getString("password");
                txt_password.setText(add12);
                lbl_password.setText(add12);
                byte[] imagedata=rs.getBytes("image");
                format =new ImageIcon(imagedata);
                image.setIcon(format);
                
                String add11=rs.getString("About");
                txt_about.setText(add11);
                lbl_about.setText(add11);
              }}catch(Exception e){
                  JOptionPane.showMessageDialog(null, e);
              }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
          }
    }//GEN-LAST:event_Table_EmployeeKeyReleased
    }
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       gender="male"; // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        gender="female";
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               /* if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
                 UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
          catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cmd_clear;
    private javax.swing.JButton Cmd_delete;
    private javax.swing.JButton Cmd_print;
    private javax.swing.JButton Cmd_save;
    private javax.swing.JComboBox ComboBox_name;
    private javax.swing.JTable Table_Employee;
    private javax.swing.JTextArea Text;
    private javax.swing.JTextField To;
    private javax.swing.JLabel all_messages;
    private javax.swing.JButton attach;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox combo_post;
    private javax.swing.JLabel content_message;
    private javax.swing.JMenu date_txt;
    private javax.swing.JButton fetch_inbox;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private com.toedter.calendar.JDateChooser join_date;
    private javax.swing.JLabel lbl_EmpID;
    private javax.swing.JLabel lbl_about;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_age;
    private javax.swing.JLabel lbl_contact;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_joindate;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_post;
    private javax.swing.JLabel lbl_surname;
    private javax.swing.JTextField name_attach;
    private javax.swing.JTextField path_attach;
    private javax.swing.JTextField subject;
    private javax.swing.JMenu time_txt;
    private javax.swing.JTextField txt_EmpID;
    private javax.swing.JTextArea txt_about;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_filepath;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JButton txt_update;
    // End of variables declaration//GEN-END:variables
 private ImageIcon format=null;
 String filename=null;
 byte[] person_image=null;
 String attachment_path;
 private String gender;
}
